# This file contains values from Cookiecutter

default_context:
  project_name: "mlops"
  repo_name: "mlops_training"
  description: "Contents for mlops workshop"
  organization: "Fraunhofer AICOS"
  license: "No license"
  organization_email: "no-reply@fraunhofer.pt"
  line_length: "120"
  python_minimal_version: "3.8"
